apiVersion: v1
kind: Service
metadata:
  name: appsimulate
  namespace: appsimulate
  annotations:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: appsimulate
  ports:
    - name: app-port
      protocol: TCP
      port: 5000
      targetPort: 5000