apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-simulate
  namespace: request-simulate
  labels:
    app: request-simulate
  annotations:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-simulate
  template:
    metadata:
      labels:
        app: request-simulate
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: request-simulate
        image: 832438989008.dkr.ecr.ap-southeast-1.amazonaws.com/request-simulate@sha256:70ebd4741f7c3931e1666686378185b1ebd25790c459d4445df68bdbd23fd716
        ports:
        - name: prometheus
          containerPort: 8000
        livenessProbe:
          exec:
            command:
            - cat
            - /app/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /healthz/ready
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
