apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-loadtest
  namespace: app-loadtest
  labels:
    app: app-loadtest
  annotations:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-loadtest
  template:
    metadata:
      labels:
        app: app-loadtest
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: app-loadtest
        image: 832438989008.dkr.ecr.ap-southeast-1.amazonaws.com/app-loadtest@sha256:b58e45cf7809394590e449719f3b8c6c053630e6a3947363778310dfa035a282
        ports:
        - name: prometheus
          containerPort: 8000
        livenessProbe:
          exec:
            command:
            - cat
            - /app/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /healthz/ready
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
