apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-loadtest
  namespace: app-loadtest
  labels:
    app: app-loadtest
  annotations:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-loadtest
  template:
    metadata:
      labels:
        app: app-loadtest
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: app-loadtest
        image: 832438989008.dkr.ecr.ap-southeast-1.amazonaws.com/app-loadtest@sha256:fe22b101168b50d202579c9b558a8e8f0a5dcbacfc21a3f5e9fb28fa5062c60c
        ports:
        - name: prometheus
          containerPort: 8000
        livenessProbe:
          exec:
            command:
            - cat
            - /app/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
