apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-loadtest
  namespace: app-loadtest
  labels:
    app: app-loadtest
  annotations:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-loadtest
  template:
    metadata:
      labels:
        app: app-loadtest
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app-loadtest
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: app-loadtest
        image: 832438989008.dkr.ecr.ap-southeast-1.amazonaws.com/app-loadtest@sha256:7ae3c0d1436c21fabbea6af8a2615ba1cd80fcbfc724ae2cf72bc8bc41fcf6a5
        ports:
        - name: prometheus
          containerPort: 8000
        livenessProbe:
          exec:
            command:
            - cat
            - /app/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
