prometheus-adapter:
  prometheus:
    url: http://prometheus.istio-system.svc.cluster.local
    port: 9090
    path: ""
  rules:
    default: true
    external:
    - seriesQuery: 'predicted_prometheus{job="predict-controller", namespace="app-simulate", pod="app-simulate"}'
      metricsQuery: 'sum(predicted_prometheus{job="predict-controller"})'
      resources:
        namespaced: false
    - seriesQuery: 'predicted_prometheus_tolerate{job="predict-controller", namespace="app-simulate", pod="app-simulate"}'
      metricsQuery: 'sum(predicted_prometheus_tolerate{job="predict-controller"})'
      resources:
        namespaced: false