apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus
  namespace: istio-system
spec:
  hosts:
  - 'prometheus.khanh-thesis.online'
  gateways: 
    - istio
  http:
    - name: "prometheus"
      route:
        - destination:
            port:
              number: 9090
            host: prometheus.istio-system.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "prometheus.khanh-thesis.online"
