apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-controller
  namespace: predict-controller
  labels:
    app: predict-controller
  annotations:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predict-controller
  template:
    metadata:
      labels:
        app: predict-controller
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: predict-controller
        image: 832438989008.dkr.ecr.ap-southeast-1.amazonaws.com/predict-controller@sha256:4ab9e54dbce36ffb767185ea3d8ecb974f8a38b79ecef32b2b07cb71e241db2d
        ports:
        - containerPort: 8000
        livenessProbe:
          exec:
            command:
            - cat
            - /app/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /app/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
