apiVersion: v1
kind: Service
metadata:
  name: predict-controller
  namespace: predict-controller
  annotations:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: predict-controller
  ports:
    - name: predict-controller-prometheus
      protocol: TCP
      port: 8000
      targetPort: 8000
