kiali-operator:
  cr:
    create: true
    name: kiali
    # If you elect to create a Kiali CR (--set cr.create=true)
    # and the operator is watching all namespaces (--set watchNamespace="")
    # then this is the namespace where the CR will be created (the default will be the operator namespace).
    namespace: "istio-system"

    spec:
      deployment:
        accessible_namespaces:
        - '**'
